import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the {{capitalize operation_name}}Controller must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface I{{capitalize operation_name}}Controller {


{{#each headOperation}}
  {{#each this.path}}
    {{#validMethod @key}}

/**
 {{#each ../descriptionLines}}
 * {{{this}}}
 {{/each}}
 */
  public async {{../operationId}}(request: Request, toolkit: ResponseToolkit);

    {{/validMethod}}
  {{/each}}
{{/each}}

{{#each operation}}
  {{#each this.path}}
    {{#validMethod @key}}
  /**
  {{#each ../descriptionLines}}
  * {{{this}}}
  {{/each}}
  */
  public async {{../operationId}}(request: Request, toolkit: ResponseToolkit);

    {{/validMethod}}
  {{/each}}
{{/each}}
}

export { I{{capitalize operation_name}}Controller }
