{{#each swagger.components.schemas}}
import { {{@key}}Model } from './{{@key}}.model.ts';
{{/each}}

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file.
 */

export { {{#each swagger.components.schemas}}{{@key}}Model,{{/each}} }
